databases:
  - name: myndfulonboardingdb
    region: singapore
    databaseName: myndfulonboardingdb
    ipAllowList: []

services:
  - type: web
    name: myndfulonboarding
    region: singapore
    runtime: docker
    dockerfilePath: ./back/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myndfulonboardingdb
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: SECRET_KEY
        generateValue: true
